trigger:
  branches:
    include:
      - main
      - dev
      - release/*
      - feature/*
pr:
  branches:
    include:
      - main
      - dev
      - release/*
      - feature/*

pool: 
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      set -e  # Fail the pipeline if any command fails
      # Install HashiCorp GPG key and Terraform repository
      echo "Installing HashiCorp GPG key and repository..."
      wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt update && sudo apt install -y terraform

      # Change to infra_script directory and run Terraform commands
      cd ../azure_tf/ && echo "Changed to infra_script directory"
      echo "list out the files.." && ls -lrt
      echo "Terraform initialization complete" && terraform init
      echo "Terraform validate executed" && terraform validate
      echo "Terraform plan executed" && terraform plan
    displayName: 'Install Terraform and Run Terraform Commands in infra_script'
